### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by rockymontana** [vuejs/laravel-elixir-vue-2#2]
Hello.
I'm trying to get vue2 to run on Laravel (obviously).

First, I install npm packages. All according to plan.
But when I run gulp I get:

```
</path/to/project>/node_modules/laravel-elixir-vue-2/index.js:17
  return fn.call(this, file, input, output, options)
           ^

TypeError: Cannot read property 'call' of undefined
    at Object.elixir.mixins.webpack (</path/to/project>/node_modules/laravel-elixir-vue-2/index.js:17:12)
    at </path/to/project>/gulpfile.js:18:10
    at global.Elixir (</path/to/project>/node_modules/laravel-elixir/dist/index.js:21:5)
    at Object.<anonymous> (</path/to/project>/gulpfile.js:16:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
```

Here's my gulp-file:

```
const elixir = require('laravel-elixir')
require('laravel-elixir-vue-2')

elixir(function(mix) {
    mix.sass('admin/app.scss')
        .webpack('admin/app.js')
})
```

And at the LaraconEU workshop Evan said that the `require('laravel-elixir-vue-2')` needs to be within the elixir function. So I tried that too.
Like this:

```
const elixir = require('laravel-elixir')
elixir(function(mix) {
    require('laravel-elixir-vue-2')
    mix.sass('admin/app.scss')
        .webpack('admin/app.js')
})
```

Then I get:

```
gulp
<path/to/project>/node_modules/laravel-elixir-vue-2/index.js:21
  elixir.config.js.webpack.loaders.push(
                          ^

TypeError: Cannot read property 'loaders' of undefined
    at <path/to/project>/node_modules/laravel-elixir-vue-2/index.js:21:27
    at <path/to/project>/node_modules/laravel-elixir/dist/index.js:29:16
    at Array.forEach (native)
    at global.Elixir (<path/to/project>/node_modules/laravel-elixir/dist/index.js:28:24)
    at Object.<anonymous> (<path/to/project>/gulpfile.js:14:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Last is my package.json:

```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue-2": "^0.1.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^2.0.0-rc.3",
    "vue-resource": "^0.9.3",
    "vue-router": "^2.0.0-rc.3",
    "vuex": "^2.0.0-rc.5",
    "vuex-router-sync": "^3.0.0"
  }
}

```

**Comment by yyx990803** [comment]
The package has been updated a bit, make sure the version in `package.json` is `^0.2.0` rather than `^0.1.0` and it should work properly.

**Comment by rockymontana** [comment]
That did the trick! Thanks a bunch!
