### ISSUE TITLE
Elixir.ready is not a function!

### ISSUE THREAD

**Issue by maryleloisa** [vuejs/laravel-elixir-vue-2#26]
After elixir update to @6.0.0-15 I got this error:

Elixir.ready(function () {
       ^

TypeError: Elixir.ready is not a function
    at Object.<anonymous> (C:\Users\motto\Desktop\project\node_modules\laravel-elixir-vue-2\index.js:3:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\motto\Desktop\project\gulpfile.js:3:1)
    at Module._compile (module.js:573:32)

**Comment by pasqualintosh** [comment]
Actually i solved with this:

package.json
`"laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",`

gulpfile.js 
`const elixir = require('laravel-elixir');

require('laravel-elixir-vue');elixir(mix => {

    mix.sass('app.scss').webpack('app.js');

    mix.scripts( [ 'app.js', ], 'public/js' );

});`

**Comment by christophwolff** [comment]
+1

**Comment by JorgeCarmine** [comment]
I have the same problem :(

**Comment by lawsonjt** [comment]
Same.
